export type Trimestre = "I TRIMESTRE" | "II TRIMESTRE" | "III TRIMESTRE";

export interface DisciplinaRow {
  n: number;
  nome: string;
  faltasJ: string;
  faltasI: string;
  pp: string | number;
  pt: string | number;
  mt: string | number;
}

export interface BoletimData {
  trimestre: Trimestre;
  disciplinas: DisciplinaRow[];
  media: number;
}

// A nota é "negativa" se < 10
export function isNegativa(val: string | number): boolean {
  if (val === "-") return false;
  return Number(val) < 10;
}

export const BOLETIM_DATA: Record<Trimestre, BoletimData> = {
  "I TRIMESTRE": {
    trimestre: "I TRIMESTRE",
    media: 14,
    disciplinas: [
      {
        n: 1,
        nome: "PORTUGUÊS",
        faltasJ: "-",
        faltasI: "-",
        pp: 14,
        pt: 11,
        mt: 13,
      },
      {
        n: 2,
        nome: "INGLÊS",
        faltasJ: "-",
        faltasI: "-",
        pp: 18,
        pt: 9,
        mt: 14,
      },
      {
        n: 3,
        nome: "FORMAÇÃO DE ATITUDES INTEGRADORAS",
        faltasJ: "-",
        faltasI: "-",
        pp: 8,
        pt: 17,
        mt: 13,
      },
      {
        n: 4,
        nome: "EDUCAÇÃO FÍSICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 10,
        pt: 12,
        mt: 11,
      },
      {
        n: 5,
        nome: "MATEMÁTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 13,
        pt: 12,
        mt: 13,
      },
      {
        n: 6,
        nome: "FÍSICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 10,
        pt: 10,
        mt: 10,
      },
      {
        n: 7,
        nome: "QUÍMICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 19,
        pt: 20,
        mt: 20,
      },
      {
        n: 8,
        nome: "INFORMÁTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 15,
        pt: 17,
        mt: 16,
      },
      {
        n: 9,
        nome: "TÉCNICAS DE LABORATÓRIO",
        faltasJ: "-",
        faltasI: "-",
        pp: "-",
        pt: "-",
        mt: "-",
      },
      {
        n: 10,
        nome: "QUÍMICA ANALÍTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 12,
        pt: 14,
        mt: 13,
      },
      {
        n: 11,
        nome: "QUÍMICA ORGÂNICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 16,
        pt: 20,
        mt: 18,
      },
    ],
  },
  "II TRIMESTRE": {
    trimestre: "II TRIMESTRE",
    media: 15,
    disciplinas: [
      {
        n: 1,
        nome: "PORTUGUÊS",
        faltasJ: "-",
        faltasI: "-",
        pp: 15,
        pt: 13,
        mt: 14,
      },
      {
        n: 2,
        nome: "INGLÊS",
        faltasJ: "-",
        faltasI: "-",
        pp: 16,
        pt: 11,
        mt: 14,
      },
      {
        n: 3,
        nome: "FORMAÇÃO DE ATITUDES INTEGRADORAS",
        faltasJ: "-",
        faltasI: "-",
        pp: 12,
        pt: 18,
        mt: 15,
      },
      {
        n: 4,
        nome: "EDUCAÇÃO FÍSICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 14,
        pt: 13,
        mt: 14,
      },
      {
        n: 5,
        nome: "MATEMÁTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 14,
        pt: 14,
        mt: 14,
      },
      {
        n: 6,
        nome: "FÍSICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 11,
        pt: 12,
        mt: 12,
      },
      {
        n: 7,
        nome: "QUÍMICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 20,
        pt: 20,
        mt: 20,
      },
      {
        n: 8,
        nome: "INFORMÁTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 16,
        pt: 18,
        mt: 17,
      },
      {
        n: 9,
        nome: "TÉCNICAS DE LABORATÓRIO",
        faltasJ: "-",
        faltasI: "-",
        pp: "-",
        pt: "-",
        mt: "-",
      },
      {
        n: 10,
        nome: "QUÍMICA ANALÍTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 13,
        pt: 15,
        mt: 14,
      },
      {
        n: 11,
        nome: "QUÍMICA ORGÂNICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 17,
        pt: 20,
        mt: 19,
      },
    ],
  },
  "III TRIMESTRE": {
    trimestre: "III TRIMESTRE",
    media: 16,
    disciplinas: [
      {
        n: 1,
        nome: "PORTUGUÊS",
        faltasJ: "-",
        faltasI: "-",
        pp: 16,
        pt: 14,
        mt: 15,
      },
      {
        n: 2,
        nome: "INGLÊS",
        faltasJ: "-",
        faltasI: "-",
        pp: 17,
        pt: 13,
        mt: 15,
      },
      {
        n: 3,
        nome: "FORMAÇÃO DE ATITUDES INTEGRADORAS",
        faltasJ: "-",
        faltasI: "-",
        pp: 14,
        pt: 19,
        mt: 17,
      },
      {
        n: 4,
        nome: "EDUCAÇÃO FÍSICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 15,
        pt: 15,
        mt: 15,
      },
      {
        n: 5,
        nome: "MATEMÁTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 15,
        pt: 16,
        mt: 16,
      },
      {
        n: 6,
        nome: "FÍSICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 13,
        pt: 13,
        mt: 13,
      },
      {
        n: 7,
        nome: "QUÍMICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 20,
        pt: 20,
        mt: 20,
      },
      {
        n: 8,
        nome: "INFORMÁTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 17,
        pt: 19,
        mt: 18,
      },
      {
        n: 9,
        nome: "TÉCNICAS DE LABORATÓRIO",
        faltasJ: "-",
        faltasI: "-",
        pp: "-",
        pt: "-",
        mt: "-",
      },
      {
        n: 10,
        nome: "QUÍMICA ANALÍTICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 14,
        pt: 16,
        mt: 15,
      },
      {
        n: 11,
        nome: "QUÍMICA ORGÂNICA",
        faltasJ: "-",
        faltasI: "-",
        pp: 18,
        pt: 20,
        mt: 19,
      },
    ],
  },
};

// For the bar chart — uses MT values per discipline abbreviation
export const CHART_LABELS = [
  "FIS",
  "FAI",
  "PORT",
  "QUI",
  "ING",
  "INF",
  "MAT",
  "Q.ANAL",
  "ED.FIS",
];
