export type TrimestreProva = "I TRIMESTRE" | "II TRIMESTRE" | "III TRIMESTRE";
export type Calendario =
  | "1ª PROVA DOS PROFESSORES"
  | "2ª PROVA DOS PROFESSORES";

export interface ProvaSlot {
  disciplina: string | null; // null = "—"
  highlighted?: boolean; // cinza escuro (destaque da célula)
}

export interface ProvaRow {
  horario: string;
  dias: (ProvaSlot | null)[]; // index matches DIAS array
}

export interface CalendarioData {
  label: string;
  periodo: string;
  dias: string[]; // e.g. "segunda-feira dia 9"
  rows: ProvaRow[];
}

export const PROVAS_DATA: Record<
  TrimestreProva,
  Record<Calendario, CalendarioData>
> = {
  "I TRIMESTRE": {
    "1ª PROVA DOS PROFESSORES": {
      label: "1ª PROVA DOS PROFESSORES",
      periodo: "9 de fevereiro até 24 de fevereiro de 2026",
      dias: [
        "segunda-feira dia 9",
        "terça-feira dia 10",
        "quarta-feira dia 11",
        "quinta-feira dia 12",
        "sexta-feira dia 13",
        "segunda-feira dia 16",
        "terça-feira dia 17",
        "quarta-feira dia 18",
        "quinta-feira dia 19",
        "sexta-feira dia 20",
        "segunda-feira dia 23",
        "terça-feira dia 24",
      ],
      rows: [
        {
          horario: "07:00-08:35",
          dias: [
            { disciplina: "Formação de Atitudes Integradoras" },
            { disciplina: "Informática", highlighted: true },
            { disciplina: "Química Orgânica", highlighted: true },
            { disciplina: null },
            { disciplina: "Química Analítica" },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "07:50-09:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Física", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "08:40-10:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Matemática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "09:40-12:05",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Técnicas de Laboratório", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "10:30-12:05",
          dias: [
            { disciplina: null },
            { disciplina: "Inglês", highlighted: true },
            { disciplina: "Química", highlighted: true },
            { disciplina: null },
            { disciplina: "Português", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
      ],
    },
    "2ª PROVA DOS PROFESSORES": {
      label: "2ª PROVA DOS PROFESSORES",
      periodo: "3 de março até 14 de março de 2026",
      dias: [
        "segunda-feira dia 3",
        "terça-feira dia 4",
        "quarta-feira dia 5",
        "quinta-feira dia 6",
        "sexta-feira dia 7",
        "segunda-feira dia 10",
        "terça-feira dia 11",
        "quarta-feira dia 12",
        "quinta-feira dia 13",
        "sexta-feira dia 14",
        "—",
        "—",
      ],
      rows: [
        {
          horario: "07:00-08:35",
          dias: [
            { disciplina: "Formação de Atitudes Integradoras" },
            { disciplina: null },
            { disciplina: "Química Orgânica", highlighted: true },
            { disciplina: null },
            { disciplina: "Química Analítica" },
            { disciplina: null },
            { disciplina: "Informática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "07:50-09:25",
          dias: [
            { disciplina: null },
            { disciplina: "Física", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "08:40-10:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Matemática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "09:40-12:05",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Técnicas de Laboratório", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "10:30-12:05",
          dias: [
            { disciplina: "Inglês", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Química", highlighted: true },
            { disciplina: "Português", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
      ],
    },
  },
  "II TRIMESTRE": {
    "1ª PROVA DOS PROFESSORES": {
      label: "1ª PROVA DOS PROFESSORES",
      periodo: "9 de fevereiro até 24 de fevereiro de 2026",
      dias: [
        "segunda-feira dia 9",
        "terça-feira dia 10",
        "quarta-feira dia 11",
        "quinta-feira dia 12",
        "sexta-feira dia 13",
        "segunda-feira dia 16",
        "terça-feira dia 17",
        "quarta-feira dia 18",
        "quinta-feira dia 19",
        "sexta-feira dia 20",
        "segunda-feira dia 23",
        "terça-feira dia 24",
      ],
      rows: [
        {
          horario: "07:00-08:35",
          dias: [
            { disciplina: "Formação de Atitudes Integradoras" },
            { disciplina: "Informática", highlighted: true },
            { disciplina: "Química Orgânica", highlighted: true },
            { disciplina: null },
            { disciplina: "Química Analítica" },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "07:50-09:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Física", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "08:40-10:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Matemática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "09:40-12:05",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Técnicas de Laboratório", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "10:30-12:05",
          dias: [
            { disciplina: null },
            { disciplina: "Inglês", highlighted: true },
            { disciplina: "Química", highlighted: true },
            { disciplina: null },
            { disciplina: "Português", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
      ],
    },
    "2ª PROVA DOS PROFESSORES": {
      label: "2ª PROVA DOS PROFESSORES",
      periodo: "3 de março até 14 de março de 2026",
      dias: [
        "segunda-feira dia 3",
        "terça-feira dia 4",
        "quarta-feira dia 5",
        "quinta-feira dia 6",
        "sexta-feira dia 7",
        "segunda-feira dia 10",
        "terça-feira dia 11",
        "quarta-feira dia 12",
        "quinta-feira dia 13",
        "sexta-feira dia 14",
        "—",
        "—",
      ],
      rows: [
        {
          horario: "07:00-08:35",
          dias: [
            { disciplina: "Formação de Atitudes Integradoras" },
            { disciplina: null },
            { disciplina: "Química Orgânica", highlighted: true },
            { disciplina: null },
            { disciplina: "Química Analítica" },
            { disciplina: null },
            { disciplina: "Informática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "07:50-09:25",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "08:40-10:25",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "09:40-12:05",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "10:30-12:05",
          dias: Array(12).fill({ disciplina: null }),
        },
      ],
    },
  },
  "III TRIMESTRE": {
    "1ª PROVA DOS PROFESSORES": {
      label: "1ª PROVA DOS PROFESSORES",
      periodo: "1 de junho até 12 de junho de 2026",
      dias: [
        "segunda-feira dia 1",
        "terça-feira dia 2",
        "quarta-feira dia 3",
        "quinta-feira dia 4",
        "sexta-feira dia 5",
        "segunda-feira dia 8",
        "terça-feira dia 9",
        "quarta-feira dia 10",
        "quinta-feira dia 11",
        "sexta-feira dia 12",
        "—",
        "—",
      ],
      rows: [
        {
          horario: "07:00-08:35",
          dias: [
            { disciplina: "Formação de Atitudes Integradoras" },
            { disciplina: "Informática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Química Analítica" },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Química Orgânica", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "07:50-09:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Física", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "08:40-10:25",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Matemática", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "09:40-12:05",
          dias: [
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: "Técnicas de Laboratório", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
        {
          horario: "10:30-12:05",
          dias: [
            { disciplina: "Inglês", highlighted: true },
            { disciplina: null },
            { disciplina: "Química", highlighted: true },
            { disciplina: null },
            { disciplina: "Português", highlighted: true },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
            { disciplina: null },
          ],
        },
      ],
    },
    "2ª PROVA DOS PROFESSORES": {
      label: "2ª PROVA DOS PROFESSORES",
      periodo: "22 de junho até 3 de julho de 2026",
      dias: [
        "segunda-feira dia 22",
        "terça-feira dia 23",
        "quarta-feira dia 24",
        "quinta-feira dia 25",
        "sexta-feira dia 26",
        "segunda-feira dia 29",
        "terça-feira dia 30",
        "quarta-feira dia 1",
        "quinta-feira dia 2",
        "sexta-feira dia 3",
        "—",
        "—",
      ],
      rows: [
        {
          horario: "07:00-08:35",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "07:50-09:25",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "08:40-10:25",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "09:40-12:05",
          dias: Array(12).fill({ disciplina: null }),
        },
        {
          horario: "10:30-12:05",
          dias: Array(12).fill({ disciplina: null }),
        },
      ],
    },
  },
};
